package app;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;

import swing.ui.DefaultForm;
import swing.ui.DefaultList;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 * 
 * @author itakenami
 */
public class Main extends javax.swing.JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form Main
	 */

	class DispatcherListener implements KeyEventDispatcher {

		@Override
		public boolean dispatchKeyEvent(final KeyEvent e) {

			if (e.getID() == KeyEvent.KEY_RELEASED) {
				if (e.getKeyCode() == 113) {
					final DefaultList tab = (DefaultList) Main.this.tabbedCButton1.getSelectedComponent();
					if (tab != null) {
						tab.addRegister();
					}

				}
				if (e.getKeyCode() == 114) {
					final DefaultList tab = (DefaultList) Main.this.tabbedCButton1.getSelectedComponent();
					if (tab != null) {
						tab.editRegister();
					}

				}
				if (e.getKeyCode() == 27) {
					if (DefaultForm.SHOW) {
						final DefaultList tab = (DefaultList) Main.this.tabbedCButton1.getSelectedComponent();
						if (tab != null) {
							tab.getDefaultForm().closeForm();
						}
					}

				}
				return true;
			} else {
				return false;
			}

		}
	}

	public Main() {
		this.initComponents();
		final KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
		manager.addKeyEventDispatcher(new DispatcherListener());
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.tabbedCButton1 = new swing.ui.TabbedCButton();
		this.jPanel1 = new javax.swing.JPanel();
		this.menuBar = new javax.swing.JMenuBar();
		this.fileMenu = new javax.swing.JMenu();
		this.openMenuItem = new javax.swing.JMenuItem();
		this.menuItemProduto = new javax.swing.JMenuItem();
		this.exitMenuItem = new javax.swing.JMenuItem();
		this.helpMenu = new javax.swing.JMenu();
		this.contentMenuItem = new javax.swing.JMenuItem();
		this.aboutMenuItem = new javax.swing.JMenuItem();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		this.jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		final org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(this.jPanel1);
		this.jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 0, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 20, Short.MAX_VALUE));

		this.fileMenu.setMnemonic('C');
		this.fileMenu.setText("Cadastros");

		this.openMenuItem.setText("Usuarios");
		this.openMenuItem.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				Main.this.openMenuItemActionPerformed(evt);
			}
		});

		this.menuItemProduto.setText("Produtos");
		this.menuItemProduto.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				Main.this.openMenuItemActionPerformed(evt);
			}
		});

		this.fileMenu.add(this.menuItemProduto);
		this.fileMenu.add(this.openMenuItem);

		this.exitMenuItem.setMnemonic('S');
		this.exitMenuItem.setText("Sair");
		this.exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				Main.this.exitMenuItemActionPerformed(evt);
			}
		});
		this.fileMenu.add(this.exitMenuItem);

		this.menuBar.add(this.fileMenu);

		this.helpMenu.setMnemonic('h');
		this.helpMenu.setText("Ajuda");

		this.contentMenuItem.setMnemonic('c');
		this.contentMenuItem.setText("Contents");
		this.helpMenu.add(this.contentMenuItem);

		this.aboutMenuItem.setMnemonic('a');
		this.aboutMenuItem.setText("About");
		this.helpMenu.add(this.aboutMenuItem);

		this.menuBar.add(this.helpMenu);

		this.setJMenuBar(this.menuBar);

		final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(this.jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.add(this.tabbedCButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(	layout.createSequentialGroup()
								.add(this.tabbedCButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(this.jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	private void exitMenuItemActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}// GEN-LAST:event_exitMenuItemActionPerformed

	private void openMenuItemActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_openMenuItemActionPerformed

		evt.getActionCommand().equalsIgnoreCase("Produtos");

		switch (evt.getActionCommand()) {
		case "Produtos":
			this.tabbedCButton1.addTab("Produtos", Application.getInstance().listProdutos);
			this.tabbedCButton1.setSelectedComponent(Application.getInstance().listProdutos);
			break;
		default:
			this.tabbedCButton1.addTab("Usuarios", Application.getInstance().listUsuario);
			this.tabbedCButton1.setSelectedComponent(Application.getInstance().listUsuario);
			break;
		}

	}// GEN-LAST:event_openMenuItemActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(final String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (final ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				// new Main().setVisible(true);
				Application.getInstance().main.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JMenuItem contentMenuItem;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuItem openMenuItem;
	private javax.swing.JMenuItem menuItemProduto;
	private swing.ui.TabbedCButton tabbedCButton1;
	// End of variables declaration//GEN-END:variables
}
